### ISSUE TITLE
Action Lag issues

### ISSUE THREAD

**Issue by krakenx40** [bwp91/homebridge-ewelink#149] opened 2020-11-16 13:54 UTC
### What issue do you have? Please be as thorough and explicit as possible.
There is a huge lag but everything is working, its aorund 10seconds?

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
Latest

* Which version of Homebridge/HOOBS do you have?
latest

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
newest, upadated

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.
Just normal smart sockets

* Do you use your main eWeLink credentials or do you use a secondary eWeLink account for Homebridge?
main

### Please paste any relevant logs below.
<!--
   It helps if you can turn on 'Debug Logging' and 'Request & Response Logging' in the plugin settings for more thorough logging.
   If you are posting an error then it is helpful for me to also see the previous few lines as this can show the cause of the error.
   Please enter the logs between the two ``` lines below so that the logs are formatted in a way which is easier to read

**Comment by bwp91** [comment] 2020-11-16 14:12
Hi @krakenx40 
Out of interest, if you control devices through the Homebridge user interface, is there a lag?

**Comment by krakenx40** [comment] 2020-11-29 13:08
@bwp91 Yes, there is lag through the hoobs interface, I have used this plugin for a very long time in the past it was perfect, never failed, super reponsive.

**Comment by bwp91** [comment] 2020-11-29 13:43
Could you turn on Debug Logging and Request & Response Logging via the plugin settings and paste some logs of when you control a device?

**Comment by krakenx40** [comment] 2020-11-30 11:31
No Problem, here it is. Thank you for helping me @bwp91 
___________________________________________________________________
11/30/2020, 7:29:33 PM [eWeLink] LAN message sent. This text is yellow for clarity.
{
  "apikey": "**hidden**",
  "deviceid": "**hidden**",
  "params": {
    "switches": [
      {
        "switch": "off",
        "outlet": 0
      },
      {
        "switch": "off",
        "outlet": 1
      },
      {
        "switch": "off",
        "outlet": 2
      },
      {
        "switch": "off",
        "outlet": 3
      }
    ]
  }
}
11/30/2020, 7:29:48 PM [eWeLink] [Study RGB] Reverting to web socket as socket hang up.
11/30/2020, 7:29:48 PM [eWeLink] WS message sent. This text is yellow for clarity.
{
  "apikey": "**hidden**",
  "deviceid": "**hidden**",
  "params": {
    "switches": [
      {
        "switch": "off",
        "outlet": 0
      },
      {
        "switch": "off",
        "outlet": 1
      },
      {
        "switch": "off",
        "outlet": 2
      },
      {
        "switch": "off",
        "outlet": 3
      }
    ]
  },
  "action": "update",
  "sequence": "1606735788710",
  "ts": 0,
  "userAgent": "app"
}
11/30/2020, 7:29:48 PM [eWeLink] WS message received.
{
  "deviceid": "**hidden**",
  "params": {
    "online": true,
    "updateSource": "WS"
  }
}
11/30/2020, 7:29:48 PM [eWeLink] [Study RGB] WS update received and will be refreshed.
11/30/2020, 7:29:48 PM [eWeLink] LAN message received.
{
  "deviceid": "**hidden**",
  "params": {
    "switches": [
      {
        "switch": "off",
        "outlet": 0
      },
      {
        "switch": "off",
        "outlet": 1
      },
      {
        "switch": "off",
        "outlet": 2
      },
      {
        "switch": "off",
        "outlet": 3
      }
    ],
    "updateSource": "LAN",
    "online": true
  }
}
11/30/2020, 7:29:48 PM [eWeLink] [Study RGB] LAN update received and will be refreshed.
11/30/2020, 7:29:52 PM [eWeLink] LAN message sent. This text is yellow for clarity.
{
  "apikey": "**hidden**",
  "deviceid": "**hidden**",
  "params": {
    "switches": [
      {
        "switch": "on",
        "outlet": 0
      },
      {
        "switch": "off",
        "outlet": 1
      },
      {
        "switch": "off",
        "outlet": 2
      },
      {
        "switch": "off",
        "outlet": 3
      }
    ]
  }
}
11/30/2020, 7:29:57 PM [Pi Temp] Sending temp: 33.102
11/30/2020, 7:30:07 PM [eWeLink] [Study RGB] Reverting to web socket as socket hang up.
11/30/2020, 7:30:07 PM [eWeLink] WS message sent. This text is yellow for clarity.
{
  "apikey": "**hidden**",
  "deviceid": "**hidden**",
  "params": {
    "switches": [
      {
        "switch": "on",
        "outlet": 0
      },
      {
        "switch": "off",
        "outlet": 1
      },
      {
        "switch": "off",
        "outlet": 2
      },
      {
        "switch": "off",
        "outlet": 3
      }
    ]
  },
  "action": "update",
  "sequence": "1606735807706",
  "ts": 0,
  "userAgent": "app"
}
11/30/2020, 7:30:07 PM [eWeLink] WS message received.
{
  "deviceid": "**hidden**",
  "params": {
    "online": true,
    "updateSource": "WS"
  }
}
11/30/2020, 7:30:07 PM [eWeLink] [Study RGB] WS update received and will be refreshed.
11/30/2020, 7:30:07 PM [eWeLink] LAN message received.
{
  "deviceid": "**hidden**",
  "params": {
    "switches": [
      {
        "switch": "on",
        "outlet": 0
      },
      {
        "switch": "off",
        "outlet": 1
      },
      {
        "switch": "off",
        "outlet": 2
      },
      {
        "switch": "off",
        "outlet": 3
      }
    ],
    "updateSource": "LAN",
    "online": true
  }
}
11/30/2020, 7:30:07 PM [eWeLink] [Study RGB] LAN update received and will be refreshed.

**Comment by bwp91** [comment] 2020-11-30 11:40
The issue is that the plugin is trying to control to your devices over the LAN network but can’t quite connect to them. It waits the ~10 seconds before reverting to using the cloud. This explains the delay. 

Solution:
* Are your devices updated to the latest firmware?
* Can you think of any other reason why the plugin can’t connect to your devices over LAN?
* If not, then I can add an option to disable LAN mode skip the *trying over LAN*

**Comment by krakenx40** [comment] 2020-11-30 11:44
@bwp91 I am not sure why, controling the devices from the ewelink app has instantaneous reponses, and never fails. Would resetting the app help? If not, could you please add the option? Thank you so much!

**Comment by bwp91** [comment] 2020-11-30 11:50
The ewelink app directly uses the cloud.
The plugin tries to use local control first, but then reverts to the cloud. 
This is why there is a delay with the plugin. 
I'll get back to you

**Comment by krakenx40** [comment] 2020-11-30 12:00
@bwp91 is there anyway to make it use local control?

**Comment by bwp91** [comment] 2020-11-30 12:02
@krakenx40 This is why I asked if the devices are on the latest firmware?

The LAN control should be automatically on.

You can check this setting per device in the ewelink app, go to device settings and enable the option for "LAN control"

**Comment by krakenx40** [comment] 2020-11-30 13:36
@bwp91 I dont see an option for that in the ewelink app

**Comment by bwp91** [comment] 2020-11-30 13:38
Which device (product model) is it?
And is it updated with the most recent firmware?

**Comment by krakenx40** [comment] 2020-11-30 13:40
All my devices are smart plugs, yes updated to 3.3.2, the latest version

**Comment by bwp91** [comment] 2020-11-30 13:41
Yes but which brand/product models are they?

**Comment by krakenx40** [comment] 2020-11-30 13:43
Ewelink mini smart sockets

**Comment by krakenx40** [comment] 2020-11-30 13:54
I dont think there is a way to make it go LAN, can you make a option for it to go cloud control only?

**Comment by bwp91** [comment] 2020-11-30 14:25
Yes, could you upgrade to a beta version, v3.15.1-2, [using this guide](https://github.com/bwp91/homebridge-ewelink/wiki/Beta-Version).

Let me know once you have done this.

**Comment by krakenx40** [comment] 2020-12-01 11:57
Just tried it I got this error message
![image](https://user-images.githubusercontent.com/65119591/100737715-7c548600-340f-11eb-9eeb-14960f709bac.png)

**Comment by bwp91** [comment] 2020-12-01 12:03
Did you stop the hoobs service first?

**Comment by krakenx40** [comment] 2020-12-01 12:07
Yes I tried again, and it told me to also update my NPM (Using npm install -g npm), but I got this. The service is stopped. You got any idea how to run it ask root/admin?
![image](https://user-images.githubusercontent.com/65119591/100738635-d43fbc80-3410-11eb-8360-56a93d1e5c6e.png)

**Comment by krakenx40** [comment] 2020-12-01 12:08
YES YES THANK YOU SO MUCH THE PLUGIN IS PERFECTLY WORKING AGAIN SEEMLESSLY, NO LAG AT ALL THANK YOU SO MUCH FOR YOUR HELP!!!!

**Comment by bwp91** [comment] 2020-12-01 12:11
So did you turn the “disable LAN mode” setting to true?

**Comment by krakenx40** [comment] 2020-12-01 12:12
Yes, the LAN mode setting is good, but I am having a problem updating the npm of the hoobs itself, could you please help me with that?

**Comment by bwp91** [comment] 2020-12-01 12:15
Updating node will also update npm:
https://github.com/bwp91/homebridge-ewelink/wiki/How-to-update-node#hoobs

**Comment by krakenx40** [comment] 2020-12-01 12:30
Thank you so much for your help

**Comment by bwp91** [comment] 2020-12-01 12:37
You’re welcome. Stay on the beta for now and when an official release of the plugin is available, it will show as an update in hoobs.

**Comment by krakenx40** [comment] 2020-12-01 12:52
I have a new problem, I just restarted my hoobs and now there is no response to the server. 
I tried sudo hoobs service log, and this is what is showing
![image](https://user-images.githubusercontent.com/65119591/100743348-28e63600-3417-11eb-9cac-267d8774b4db.png)

**Comment by bwp91** [comment] 2020-12-01 13:07
The command on my wiki page for updating node on HOOBS is directly from hoobs support, so *should* have worked.

Looks like someone else found a solution to a similar error [on this comment](https://github.com/hoobs-org/HOOBS/issues/649#issuecomment-633205066), but your safest bet would be to get in contact with hoobs support.

I'm hesitant to suggest anything else in case it makes things worse

**Comment by bwp91** [comment] 2020-12-01 13:09
or here:
https://github.com/hoobs-org/HOOBS/issues/914

**Comment by krakenx40** [comment] 2020-12-01 13:09
Thank you for your help again!

**Comment by bwp91** [comment] 2020-12-01 15:10
You're welcome. I'll close this as I assume from the plugin perspective it's working again!

**Comment by krakenx40** [comment] 2021-01-24 02:22
Hi, I just updated my plugin, and I am having the same problem again, could you please consider adding it as an option to add it into the next update?

**Comment by krakenx40** [comment] 2021-01-24 02:29
@bwp91 Is it possible for me to revert back to the  v3.15.1-2 beta, since that was working very well for me? I dont see a restore buttonn since im on hoobs :(

**Comment by bwp91** [comment] 2021-01-24 08:49
Hi @krakenx40 

Please can you paste the ewelink part of your hoobs config? Remove your username and password of course! There have been a few config changes recently and just want to make sure you're up-to-date as this may be why you are experiencing the lag again.

**Comment by krakenx40** [comment] 2021-01-24 12:34
Of course! Here it is
{
            "platform": "eWeLink",
            "plugin_map": {
                "plugin_name": "homebridge-ewelink-max"
            },
            "name": "eWeLink",
            "debug": false,
            "debugReqRes": false,
            "disableHTTPRefresh": false,
            "disablePlugin": false,
            "inUsePowerThreshold": 0,
            "lowBattThreshold": 25,
            "sensorTimeDifference": 0,
            "hideZBLDPress": false,
            "countryCode": "86",
            "username": "XXXXXXXX",
            "password": "XXXXXXXXXXXXX",
            "disableLANMode": true
        },

**Comment by bwp91** [comment] 2021-01-24 12:45
You can strip this down to:

```json
   {
      "platform": "eWeLink",
      "plugin_map": {
      "plugin_name": "homebridge-ewelink-max"
   },
   "name": "eWeLink",
   "countryCode": "86",
   "username": "XXXXXXXX",
   "password": "XXXXXXXXXXXXX",
   "mode": "wan"
},
```

The `plugin_name` _should_ be `homebridge-ewelink`, but I'm hesitant to change it if it's working already.

The last option I have added, `"mode": "wan",` should stop the lagging again.

**Comment by krakenx40** [comment] 2021-01-24 12:54
I just tried it, but there is still a lag.

**Comment by krakenx40** [comment] 2021-01-24 12:56
Yes it working agian, Thank you so much!

**Comment by bwp91** [comment] 2021-01-24 12:58
Fab. I’ll close this issue again!

**Closed as completed by bwp91** 2021-01-24 12:58 UTC
