### ISSUE TITLE
Garage door stuck closing or opening

### ISSUE THREAD

**Issue by zelik888** [bwp91/homebridge-ewelink#406] opened 2022-08-31 10:08 UTC
### What issue do you have? Please be as thorough and explicit as possible.
Garage door simulation with Sonoff 3Channel works to open/close from HomeKit but somehow will keep saying “Opening…” or “Closing…” indefinitely. 

I have paired it with a DW2-RF contact sensor and inputted it in the settings, no change. Removing sensor and it still is stuck opening or closing message. Very strange. 

In the past, without the sensor, it would change to Open or Close after the specified seconds in Operation time. Now it just stays indefinitely in the opening/closing. If I press it again it’ll operate the sonoff (go from closing to opening and Vice versa) but the status stays stuck. 

Things Ive tried:
Removing bridge
Delete cache for sonoff 3CH
Delete plugin and config in homebridge 
Remove/re-add bridge to HomeKit 

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 

Homebridge 

* Which version of Homebridge/HOOBS do you have?

1.50

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

10.0.0. I’m not sure, but it used to work. Not sure if this is due to newer version or not. 

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

Sonoff 3CH (HC-3CH-E (3))

* Do you use your main eWeLink credentials or do you use a secondary eWeLink account for Homebridge?

Main credentials 

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment] 2023-03-11 05:25
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!

**Closed as completed by bwp91** 2023-03-11 05:25 UTC

**Comment by or-agami** [comment] 2024-10-27 21:12
@bwp91 Im experiencing the same issue, suddenly the status is “closing” I’m not sure what’s the cause or how to reproduce, the status is correct in ewelink app it’s resolving after HomeBridge restart.

If I’m not mistaken the issue started 3 months ago, nothing was changed in my setup
