### ISSUE TITLE
Sonoff Micro USB

### ISSUE THREAD

**Issue by dedyushin** [bwp91/homebridge-ewelink#159] opened 2020-12-03 19:59 UTC
* **Please explain your feature request in a one or two sentences.**

Hello! I am looking for support of Sonoff Micro USB wifi controller. It doesn't recognized by HB and HK.  

* **Is your feature request related to a problem? Please describe.**

* **Any particular eWeLink devices that this relates to?**

Sonoff Micro USB WiFi controller

* **Anything else?**

**Comment by bwp91** [comment] 2020-12-03 20:10
Duplicate of #158. Please follow the conversation there. thanks

**Closed as completed by bwp91** 2020-12-03 20:10 UTC
