### ISSUE TITLE
SW0, SW1 and SW2 on the Sonoff with 2 channels

### ISSUE THREAD

**Issue by martonky** [bwp91/homebridge-ewelink#93] opened 2020-09-18 21:10 UTC
Hi guys,

at first, I would like to say many thanks for this plugin. Great job! I am using Homebridge on Raspberry. 

I d like to ask, why I see SW0 on the Sonoff TX2C EU. This Sonoff has 2 channels and I see 3 lights at homekit (SW0, SW1 and SW2). At cachcedAccessories I can see also SW0, SW1 and SW2.

Remote controll:

1. SW0 - remoting 2 channels at the same time,
2. SW1 - remoting 1 channel,
3. SW2 - remoting 1 channel.

I tried do hide SW0 across hideFromHB but it didn t work.

Here is my code at homebridge:

{
            "platform": "eWeLink",
            "name": "eWeLink",
            "username": "(secret)",
            "password": "(secret)",
            "countryCode": "+421",
            "10009553c8": "192.168.(secret).(secret)",
            "hideFromHB": "100093f139SW0"
        }

...

I am using the last update of homebridge

...

v2.27.2

...

**Comment by Lazyass0** [comment] 2020-09-18 21:17
https://github.com/bwp91/homebridge-ewelink/wiki/Roadmap

**Comment by bwp91** [comment] 2020-09-18 21:19
I think I need to document this better. SW0 cannot currently be hidden, only SW number 1, 2, 3, 4.
This is due to to technicalities. 
As im writing this @Lazyass0 has sent a link which is helpful!

**Comment by bwp91** [comment] 2020-09-18 21:23
To clarify:
SW0 is an "invented" accessory that controls both channels.
SW1 is for channel 0
SW2 is for channel1.

When I started with this plugin it was basically just to suit me .... and I added this "SW0" for help with automations.

Hiding it is something I am looking into :)

**Comment by martonky** [comment] 2020-09-19 18:02
Ok, guys. Thank you very much for the answers.

Maybe, it will be better if I am introduce, why I am trying to set Sonoff only for SW1 and SW2. Until the wednesday I was using plugin homebridge-ewelink-krasnov. It was working stable relatively. I had a problem fictive CH3 and CH4 on my 2 channels Sonoff. This time I solved the problem with modify cachedAccessories. Some time after connecting the device to HomeKit, a second cache of this device was created in the homebridge cachedAccessories file and homebridge crashed.

The reason, why I migrate to your plugin is that I need to controll sonoff via LAN. At now, I can't see logs from ewelink plugin at Homebridge Config UI X, and I can not indetify, why my inteligent house making bugs. According to logs, everything is fine, but sometime I can not remote hole inteligent house.

**Comment by bwp91** [comment] 2020-09-19 18:19
Plugin logging can be enabled through the plugin settings in the “Optional” section,
* turning “Debug Logging” on.
When you say you have “bugs”/issues in your home, what exactly do you mean?
It’s very hard for me to understand and be able to correct an issue if I don’t know exactly what the issue is.
But if you turn on the logging then it might help to see what’s going on/wrong in your smart home.
Thanks

**Comment by martonky** [comment] 2020-09-19 18:24
> Plugin logging can be enabled through the plugin settings in the “Optional” section,
> 
> * turning “Debug Logging” on.
> 
> When you say you have “bugs”/issues in your home, what exactly do you mean?
> It’s very hard for me to understand and be able to correct an issue if I don’t know exactly what the issue is.
> But if you turn on the logging then it might help to see what’s going on/wrong in your smart home.
> Thanks

Thank you for the answer. Ok, I turned on Debug Logging. I will be watching what is wrong and tomorrow I will write a response.

**Comment by martonky** [comment] 2020-09-20 13:15
I am watching behaviour. For me is very interesting these things:

1. In logs looks everything is fine.
2. Maybe one later after homebridge restart goes something wrong. I set philips hue dimmer accross homekit. On the fourth button I have scene, where I set turn off one channel fo Sonoff. First hour is working fine, but after one hour when I pushed fourth button on philips hue dimmer, only few lights was going off. The channel on Sonoff stayed on. I tried to click the fourth button again but without change.
3. I opened the homekit aplication on iOS and checked the setting of philips hue dimmer. I saw the respon animation when I was clicking on fourth button where I set turn off of Sonoff channel. And here is the point, when I tried the push ,,Test scene" via Homekit aplication, It was working.
4. The fourth button started to work after apple tv/homebridge restart.

Why I am writing something what is not related to your plugin? Here is the point. After I remove part of eweling plugin from confing.json, everything is stable in my inteligent house near 6 hours.

I have suspicion, that it might be something wrong with LAN communication. Why I am seeing information about 4 outlets? Thats happend when I clicked on SW0 at homekit aplication.

`[9/20/2020, 14:05:50] [eWeLink] LAN message sent. This text is yellow for clarity.
{
  "apikey": "**hidden**",
  "deviceid": "**hidden**",
  "params": {
    "switches": [
      {
        "switch": "on",
        "outlet": 0
      },
      {
        "switch": "on",
        "outlet": 1
      },
      {
        "switch": "on",
        "outlet": 2
      },
      {
        "switch": "on",
        "outlet": 3
      }
    ]
  }
}
[9/20/2020, 14:05:50] [eWeLink] LAN message received.
{
  "deviceid": "**hidden**",
  "action": "update",
  "params": {
    "switches": [
      {
        "switch": "on",
        "outlet": 0
      },
      {
        "switch": "on",
        "outlet": 1
      },
      {
        "switch": "on",
        "outlet": 2
      },
      {
        "switch": "on",
        "outlet": 3
      }
    ],
    "updateSource": "LAN"
  }
}
[9/20/2020, 14:05:50] [eWeLink] [Bathroom] externally updated from above LAN message and will be refreshed.
[9/20/2020, 14:05:50] [eWeLink] WS message received.
{
  "deviceid": "**hidden**",
  "action": "update",
  "params": {
    "switches": [
      {
        "switch": "on",
        "outlet": 0
      },
      {
        "switch": "on",
        "outlet": 1
      },
      {
        "switch": "on",
        "outlet": 2
      },
      {
        "switch": "on",
        "outlet": 3
      }
    ],
    "updateSource": "WS"
  }
}
[9/20/2020, 14:05:50] [eWeLink] [Bathroom] externally updated from above WS message and will be refreshed.
[9/20/2020, 14:05:50] [eWeLink] LAN message received.
{
  "deviceid": "**hidden**",
  "action": "update",
  "params": {
    "switches": [
      {
        "switch": "on",
        "outlet": 0
      },
      {
        "switch": "on",
        "outlet": 1
      },
      {
        "switch": "on",
        "outlet": 2
      },
      {
        "switch": "on",
        "outlet": 3
      }
    ],
    "updateSource": "LAN"
  }
}
[9/20/2020, 14:05:50] [eWeLink] [Bathroom] externally updated from above LAN message and will be refreshed.
[9/20/2020, 14:05:51] [eWeLink] LAN message received.
{
  "deviceid": "**hidden**",
  "action": "update",
  "params": {
    "switches": [
      {
        "switch": "on",
        "outlet": 0
      },
      {
        "switch": "on",
        "outlet": 1
      },
      {
        "switch": "on",
        "outlet": 2
      },
      {
        "switch": "on",
        "outlet": 3
      }
    ],
    "updateSource": "LAN"
  }
}
[9/20/2020, 14:05:51] [eWeLink] [Bathroom] externally updated from above LAN message and will be refreshed.
[9/20/2020, 14:05:51] [eWeLink] LAN message received.
{
  "deviceid": "**hidden**",
  "action": "update",
  "params": {
    "switches": [
      {
        "switch": "on",
        "outlet": 0
      },
      {
        "switch": "on",
        "outlet": 1
      },
      {
        "switch": "on",
        "outlet": 2
      },
      {
        "switch": "on",
        "outlet": 3
      }
    ],
    "updateSource": "LAN"
  }
}
[9/20/2020, 14:05:51] [eWeLink] [Bathroom] externally updated from above LAN message and will be refreshed.`

**Comment by bwp91** [comment] 2020-09-20 13:39
> I have suspicion, that it might be something wrong with LAN communication. Why I am seeing information about 4 outlets? Thats happend when I clicked on SW0 at homekit aplication.

Nothing to worry about the fact you can see four outlets. The multi-channel sonoff devices use hardware with four channels, even if only two or three are actually used. The "redundant" ones can be set to anything (ie on/off) without affecting the plugin/devices

**Comment by bwp91** [comment] 2020-09-20 13:42
And the issue you have with the automation stopping working after a few hours, sounds more like an issue with perhaps your home hub or connectivity? The fact that there are no errors showing up in the logs, and the fact that when you "Test Automation" it works properly, makes me believe it isn't an issue with the plugin.

**Comment by bwp91** [comment] 2020-09-20 13:44
In the situation where you press the button on the philips hue dimmer and the sonoff light doesnt turn off, are there any messages in the log about a LAN mode message being sent?

**Comment by bwp91** [comment] 2020-09-20 14:42
i also have a new test version of this plugin which supports hiding the SW0 accessories if you'd be interested in testing?

**Comment by martonky** [comment] 2020-09-20 20:19
I think that I find the problem. I deleted "10009553c8": "192.168.(secret).(secret)", and all devices in the network are working fine (include philips hue dimmer). 👍 thank you very much for the support. You are doing the great job!

Small feedback: maybe to the decription you can add that is not neccessary to add IP to the config.json, when the people want to remote Sonoff via LAN.

Anyway, I can make a test of your test version bwp91.

**Comment by bwp91** [comment] 2020-09-21 08:29
Could you assign your Sonoff TX device a fixed IP from your router?

**Comment by martonky** [comment] 2020-09-21 09:44
Sonoff TX IP adress is fixed. I am using that long time because of mqtt bridge or LG TV. Anyway, I have 3 sonoff mini and 3 sonoff basic who have Tasmota. Sonoff TX is only one at my network what I am testing with official firmwere.

**Comment by martonky** [comment] 2020-09-22 17:26
I am testing your beta version. Since I was starting with 3.0.0.1, everything is working fine. For me is one interesting question for unstable behaviour from 2.27.2. When I started with beta version, I did one change in my iPhone. I logged out ewelink aplication. Can it have an affect to stability?

**Comment by bwp91** [comment] 2020-09-22 17:29
Are you using the latest version of the ewelink app on your iphone?

**Comment by martonky** [comment] 2020-09-22 17:34
It was 4.4.0. I see that the last update to 4.5.0 was 17 hours ago.

**Comment by bwp91** [comment] 2020-09-22 18:20
If you find it more stable logged out of the ewelink app then a suggestion is:
- create a second ewelink account 
- share the devices to this account
- use your main ewelink account details in Homebridge so you have access to LAN mode (as i'm almost certain LAN mode won't work with shared devices)
- log back into ewelink app with your second account

**Comment by bwp91** [comment] 2020-09-22 18:21
Anyway i'm going to close this issue now since:
- the original concern was hiding SW0 accessories
- this is now possible in the beta and will be generally available with the v3.0 release

Any other issues/comments please create a new dedicated issue or reply in the beta issue 😀

**Closed** 2020-09-22 18:21 UTC
Labels: new feature
