### ISSUE TITLE
Rf bridge on hoobs

### ISSUE THREAD

**Issue by zilnik1234** [bwp91/homebridge-ewelink#118] opened 2020-10-25 10:14 UTC
Is it possible to setup sensors from rf bridge in hoobs? 
...
Rf Bridge

**Anything else?**
...

**Comment by bwp91** [comment] 2020-10-25 11:10
Hi, do you mean set them up as a different type to motion, eg a contact sensor? Yes you should definitely be able to do this through the plugin settings section

**Comment by zilnik1234** [comment] 2020-10-25 12:14
In hoobs there is no settings section for this.. i only see them as motion sensors in home app.

**Comment by bwp91** [comment] 2020-10-25 12:26
Could you attach a screenshot of the plugin settings screen you can see? Please delete any ewelink credentials first!

**Comment by zilnik1234** [comment] 2020-10-25 12:36
<img width="821" alt="Screenshot 2020-10-25 at 14 34 16" src="https://user-images.githubusercontent.com/73424158/97107274-5c72c980-16cf-11eb-9597-78f6e4a752c6.png">
<img width="799" alt="Screenshot 2020-10-25 at 14 34 24" src="https://user-images.githubusercontent.com/73424158/97107277-60065080-16cf-11eb-887c-771086cd053d.png">11 
<img width="871" alt="Screenshot 2020-10-25 at 14 34 32" src="https://user-images.githubusercontent.com/73424158/97107278-609ee700-16cf-11eb-815a-ef5ce53cfd16.png">

Also i have 11 devices in rf bridge and i only see 9 of them in homeapp and none of them are working when i trigger..

**Comment by bwp91** [comment] 2020-10-25 16:01
You'll need to edit the last section, the `Sensors` box. You can refer to the [configuration page](https://github.com/bwp91/homebridge-ewelink/wiki/Configuration) in the wiki for more information (near the bottom, the `bridgeSensors` section).

The example given is:
```
[
   {
      "deviceId": "10009553c8",
      "type": "water",
      "fullDeviceId": "10009553c8SW1"
   },
   {
      "deviceId": "10009553c8", 
      "type": "contact",
      "fullDeviceId": "10009553c8SW2"
   }
]
```

replacing the `deviceId` with the ewelink device id of your rf bridge, the `type` can be `water`, `smoke`, `co`, `co2`, `contact`, `occupancy` or `motion`. The `fullDeviceId` is the serial number of the device in HOOBS which is the serial number of the rf bridge with SW# on the end where # is a digit.

**Comment by bwp91** [comment] 2020-10-25 16:03
> Also i have 11 devices in rf bridge and i only see 9 of them in homeapp

When you restart HOOBS and look in the logs you'll see a list of devices that have been added to HOOBS. Do the two missing ones appear there?

> none of them are working when i trigger..

If this is still happening then I can look into this further. Let's get the other two things above sorted first 👍

**Comment by zilnik1234** [comment] 2020-10-25 16:52
Ok, thank's for the sensor box exemple, it worked now and i can assign the types. 

i still have 9 out of 11 rf sensors and none it's working in home app
i looked in log and i have this error:
  [eWeLink]  → [RF bridge01] could not be initialised as Cannot read property 'name' of undefined.

maybe it's related to something..

and also i found this:
[eWeLink] [12] eWeLink devices loaded from the Homebridge cache.
25/10/2020, 18:40:28 [eWeLink] [4] primary devices loaded from your eWeLink account.

were the 4 primary are the ip devices i use - basic relays


thank you

**Comment by bwp91** [comment] 2020-10-25 16:58
If you have 4 basic relays and an RF bridge then it should say [5] primary devices loaded...?

The two devices that aren't showing in HOOBS, which device type are they? Are they RF remote buttons as opposed to sensors?

**Comment by zilnik1234** [comment] 2020-10-25 17:02
sorry i have 3 relays and one rf online..

in rf i have only alarms..sensors like

**Comment by bwp91** [comment] 2020-10-25 17:11
Would you be happy to share your rf bridge with my ewelink account so I can try sort this out much more quickly than constant going back and forth?

**Comment by zilnik1234** [comment] 2020-10-25 17:13
Yes, sure thing

**Comment by bwp91** [comment] 2020-10-25 17:13
Awesome. Which country are you based? (not a random question - need to know for sharing purposes!)

**Comment by zilnik1234** [comment] 2020-10-25 17:14
Romania EU

**Comment by bwp91** [comment] 2020-10-25 17:14
Please share to country code 44 (UK)
Email bwp91@icloud.com

**Comment by zilnik1234** [comment] 2020-10-25 17:17
done

**Comment by bwp91** [comment] 2020-10-25 17:18
got it thanks. ill get back to you!

**Comment by bwp91** [comment] 2020-10-25 17:34
The issue is that you have more than 9 devices connected to your rf bridge. a situation i have never encountered so never realised there was an issue here.

Nothing irreparable, I'll get this sorted 👍

**Comment by bwp91** [comment] 2020-10-25 17:42
Could you activate one of the sensors for me to check something?

**Comment by bwp91** [comment] 2020-10-25 17:51
Working!

**Comment by zilnik1234** [comment] 2020-10-25 17:51
Cool

**Comment by bwp91** [comment] 2020-10-25 17:55
I'll release an update in a few minutes but the update will take some time to appear in HOOBS. Then you'll be able to update and it should be working for you :) I'd like to suggest keeping the rf bridge shared with me, until you're happy its working. then feel free to unshare!

**Comment by zilnik1234** [comment] 2020-10-25 17:58
Perfect! You're awesome!

**Comment by zilnik1234** [comment] 2020-10-25 17:59
How many devices are now possible in rf bridge?

**Comment by bwp91** [comment] 2020-10-25 18:02
No limit from the plugin perspective now, but I'm not sure if there is a limit through ewelink?

**Comment by zilnik1234** [comment] 2020-10-25 18:04
Cool!

**Comment by bwp91** [comment] 2020-10-25 18:04
Once you've updated to v3.8.3, please confirm if it's working or not and I can look to close this issue.
Thanks!

**Comment by zilnik1234** [comment] 2020-10-25 18:15
Ok, can't wait :) it's a matter of minutes, hours, days..until
It will be available in hoobs? Or is there a workaround to manually update? Maybe uninstall..and install again?

**Comment by bwp91** [comment] 2020-10-25 18:23
That's a question you'll have to ask to HOOBS directly as this im unsure about and completely out of my control

**Comment by zilnik1234** [comment] 2020-10-25 19:36
Ok, i updated now and it's working almost perfect.. but.. I added another 4 sensors and deleted 'my remote' in ewe app. In home app 'my remote'device is still visible, first new device added is not visible at all and the other 3 are not updating the status.

**Comment by bwp91** [comment] 2020-10-25 19:38
Have you tried restarting HOOBS?

**Comment by zilnik1234** [comment] 2020-10-25 19:41
Yes

**Comment by bwp91** [comment] 2020-10-25 19:49
Okay, in this situation the solution might be to uninstall and reinstall the plugin. The plugin doesn't deal very well with changes in devices to the RF bridge, something I have never worked on because generally people don't remove and add devices on the go.

But if you uninstall and reinstall remember that your config for the plugin might get wiped so take a copy and paste.

**Comment by zilnik1234** [comment] 2020-10-25 20:03
i just did this and it's the same.. actualy when i uninstalled the plugin the devices where still in home app..i rebut twice the hoobs and same thing.. i reinstalled after and they started to work..but with the same thing in rf bridge.

**Comment by zilnik1234** [comment] 2020-10-25 21:07
Ok, i solve it..i disable the plugin and enable it from dropdown section.. it worked! But now the triggers are messed up.the ewe app show correctly the trigger but the home app is showing other sensor.. exemple i expose no11 sensor and in home app is trggered no3. When i expose no12 nothing triggers in home app. When i expose no13 in home app no7. When i expose no 14 in home app is no1.. the rest of them are ok aparently..

**Comment by bwp91** [comment] 2020-10-26 06:20
Please try v3.8.4 once it appears in HOOBS

**Comment by zilnik1234** [comment] 2020-10-26 18:38
It's working perfectly! Super! Nice job! Thank you very much for your time!

**Comment by bwp91** [comment] 2020-10-27 05:24
Super. I'm happy it's working for you 🙂

**Comment by bwp91** [comment] 2020-10-27 05:24
Don't forget to unshare the device!

**Closed as completed** 2020-10-27 05:25 UTC

**Comment by zilnik1234** [comment] 2020-10-27 08:05
Ok..another issue..i put a new sensor in rf bridge and is not triggering..maybe is an issue related to new sensors. 
 also it will be nice in the future that you can separate the sensor lenght time  input in config related with the sensor type.. for ex a water sensor can stay more time and a door sensor less..

**Comment by bwp91** [comment] 2020-10-27 08:13
> Ok..another issue..i put a new sensor in rf bridge and is not triggering..maybe is an issue related to new sensors.

Best to set up all the sensors you want and then do a plugin reset, ie, set `disablePlugin`to true, then to false again. As I mentioned before, the plugin doesn't deal with changes to the RF bridge very well.

In a future update I'll add an option that if true will just remove and readd the rf bridge, rather than removing and readding all devices.

> also it will be nice in the future that you can separate the sensor lenght time input in config related with the sensor type.. for ex a water sensor can stay more time and a door sensor less..

And i'll look into this too

**Comment by zilnik1234** [comment] 2020-10-27 08:30
Ok! Thanks a lot

**Comment by bwp91** [comment] 2020-10-27 10:59
Ideally I'd like to test some changes I've made. Any chance you could share the bridge with me again? And could we message on the [Homebridge Discord](https://discord.gg/7X36mdw)?
