### ISSUE TITLE
Hombridge Ewelink R5

### ISSUE THREAD

**Issue by didaspl** [bwp91/homebridge-ewelink#434] opened 2022-11-24 15:29 UTC
Hi. i Love Yours plugin - Can You let me know will Sonoff R5 (button - 9 click Scene Switch) be suported soon ?

I can see my M5 at Homekit.... But R5 is showink as 1 click button and only configuration is 1 clic 2 clic 3 clic... 

Or is any way to ad R5 as 9 single buttons?

**Comment by bwp91** [comment] 2022-11-24 18:39
Hi @didaspl 

Closing this as duplicate of https://github.com/bwp91/homebridge-ewelink/issues/430

Please see my comments on this ticket ^.

**Closed as completed by bwp91** 2022-11-24 18:39 UTC
